# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
#  push:
#    paths:
#    - 'spring-boot/**'
#    branches: [ main ]
  pull_request:
    paths:
    - 'spring-boot/**'
    - '.github/workflows/*.yml'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./spring-boot
    - name: Build with Gradle
      env:
        PR_NUMBER: ${{ github.event.number }}
        PR_ACTION: ${{ github.event.action }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_USER: ${{ github.event.pull_request.user.login }}
        PR_USER: ${{ github.event.pull_request.html_url }}
      run: ./gradlew build
      working-directory: ./spring-boot
